// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabkwiK-0de174_aCuiiWQmnsa5Yv8-QA',
    appId: '1:80738349766:web:71af77d283f65db1f19dc7',
    messagingSenderId: '80738349766',
    projectId: 'fasum-app2-662f3',
    authDomain: 'fasum-app2-662f3.firebaseapp.com',
    storageBucket: 'fasum-app2-662f3.firebasestorage.app',
    measurementId: 'G-FN31PWSRFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_SXGSVkjrl08zXCEU32tsvnwizD8c3M',
    appId: '1:80738349766:android:1c090030babdf0d2f19dc7',
    messagingSenderId: '80738349766',
    projectId: 'fasum-app2-662f3',
    storageBucket: 'fasum-app2-662f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzFFGFPuVLOXLEIkH7Ii0WQPMMBOo4kmI',
    appId: '1:80738349766:ios:aa04edcca81c8f0af19dc7',
    messagingSenderId: '80738349766',
    projectId: 'fasum-app2-662f3',
    storageBucket: 'fasum-app2-662f3.firebasestorage.app',
    iosBundleId: 'com.example.fasum2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzFFGFPuVLOXLEIkH7Ii0WQPMMBOo4kmI',
    appId: '1:80738349766:ios:aa04edcca81c8f0af19dc7',
    messagingSenderId: '80738349766',
    projectId: 'fasum-app2-662f3',
    storageBucket: 'fasum-app2-662f3.firebasestorage.app',
    iosBundleId: 'com.example.fasum2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabkwiK-0de174_aCuiiWQmnsa5Yv8-QA',
    appId: '1:80738349766:web:9cacee941eeb10b6f19dc7',
    messagingSenderId: '80738349766',
    projectId: 'fasum-app2-662f3',
    authDomain: 'fasum-app2-662f3.firebaseapp.com',
    storageBucket: 'fasum-app2-662f3.firebasestorage.app',
    measurementId: 'G-K35X2S4CTP',
  );
}
